/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

/**
 *
 * @author ELIAS
 */
public class calculadora extends javax.swing.JFrame {

    ScriptEngineManager sem = new ScriptEngineManager();
    ScriptEngine se = sem.getEngineByName("JavaScript");
    String resultado;
    boolean activo = false;

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(120, 120, 120));
        this.setSize(290, 474);
        this.setTitle("Calculadora - 162158");
        this.setVisible(true);
    }

    public void agregarNumero(String num) {
        lblSecundario.setText(lblSecundario.getText() + num);
        btnIgual.doClick();
    }

    public void actualizarNumeros() {

        try {
            int resbin = Integer.parseInt(resultado);

            String bin = Integer.toBinaryString(resbin);
            lblBinConvertido.setText(bin);
            lblDecConvertido.setText(resultado);

            int reshex = Integer.parseInt(resultado);
            String hex = Integer.toHexString(reshex);
            lblHexConvertido.setText(hex);

            int resoct = Integer.parseInt(resultado);
            String oct = Integer.toOctalString(resoct);
            lblOctConvertido.setText(oct);
        } catch (NumberFormatException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNumeros = new javax.swing.JPanel();
        btnNum1 = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnNum7 = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum9 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnNum0 = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnRetroceso = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnEspecial = new javax.swing.JButton();
        lblSecundario = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        panelEspeciales = new javax.swing.JPanel();
        btnParentesisInicio = new javax.swing.JButton();
        btnParentesisFin = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        btnPotencia = new javax.swing.JButton();
        btnComa = new javax.swing.JButton();
        panelEspeciales1 = new javax.swing.JPanel();
        lblDecTexto = new javax.swing.JLabel();
        lblOctTexto = new javax.swing.JLabel();
        lblBinTexto = new javax.swing.JLabel();
        lblHexTexto = new javax.swing.JLabel();
        lblHexConvertido = new javax.swing.JLabel();
        lblDecConvertido = new javax.swing.JLabel();
        lblOctConvertido = new javax.swing.JLabel();
        lblBinConvertido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(50, 50, 50));

        panelNumeros.setBackground(new java.awt.Color(130, 130, 130));
        panelNumeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNum1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/numero-uno.png"))); // NOI18N
        btnNum1.setBorder(null);
        btnNum1.setBorderPainted(false);
        btnNum1.setContentAreaFilled(false);
        btnNum1.setFocusPainted(false);
        btnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum1ActionPerformed(evt);
            }
        });

        btnNum2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/numero-2.png"))); // NOI18N
        btnNum2.setBorder(null);
        btnNum2.setBorderPainted(false);
        btnNum2.setContentAreaFilled(false);
        btnNum2.setFocusPainted(false);
        btnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum2ActionPerformed(evt);
            }
        });

        btnNum3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/numero-3.png"))); // NOI18N
        btnNum3.setBorder(null);
        btnNum3.setBorderPainted(false);
        btnNum3.setContentAreaFilled(false);
        btnNum3.setFocusPainted(false);
        btnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum3ActionPerformed(evt);
            }
        });

        btnNum4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/numero-cuatro.png"))); // NOI18N
        btnNum4.setBorder(null);
        btnNum4.setBorderPainted(false);
        btnNum4.setContentAreaFilled(false);
        btnNum4.setFocusPainted(false);
        btnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum4ActionPerformed(evt);
            }
        });

        btnNum5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/numero-5.png"))); // NOI18N
        btnNum5.setBorder(null);
        btnNum5.setBorderPainted(false);
        btnNum5.setContentAreaFilled(false);
        btnNum5.setFocusPainted(false);
        btnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum5ActionPerformed(evt);
            }
        });

        btnNum6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/seis.png"))); // NOI18N
        btnNum6.setBorder(null);
        btnNum6.setBorderPainted(false);
        btnNum6.setContentAreaFilled(false);
        btnNum6.setFocusPainted(false);
        btnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum6ActionPerformed(evt);
            }
        });

        btnNum7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/siete.png"))); // NOI18N
        btnNum7.setBorder(null);
        btnNum7.setBorderPainted(false);
        btnNum7.setContentAreaFilled(false);
        btnNum7.setFocusPainted(false);
        btnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum7ActionPerformed(evt);
            }
        });

        btnNum8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/numero-8.png"))); // NOI18N
        btnNum8.setBorder(null);
        btnNum8.setBorderPainted(false);
        btnNum8.setContentAreaFilled(false);
        btnNum8.setFocusPainted(false);
        btnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum8ActionPerformed(evt);
            }
        });

        btnNum9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/numero-9.png"))); // NOI18N
        btnNum9.setBorder(null);
        btnNum9.setBorderPainted(false);
        btnNum9.setContentAreaFilled(false);
        btnNum9.setFocusPainted(false);
        btnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum9ActionPerformed(evt);
            }
        });

        btnPunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/punto.png"))); // NOI18N
        btnPunto.setBorder(null);
        btnPunto.setBorderPainted(false);
        btnPunto.setContentAreaFilled(false);
        btnPunto.setFocusPainted(false);
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnNum0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/cero.png"))); // NOI18N
        btnNum0.setBorder(null);
        btnNum0.setBorderPainted(false);
        btnNum0.setContentAreaFilled(false);
        btnNum0.setFocusPainted(false);
        btnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum0ActionPerformed(evt);
            }
        });

        btnIgual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/igual.png"))); // NOI18N
        btnIgual.setBorder(null);
        btnIgual.setBorderPainted(false);
        btnIgual.setContentAreaFilled(false);
        btnIgual.setFocusPainted(false);
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/mas.png"))); // NOI18N
        btnSuma.setBorder(null);
        btnSuma.setBorderPainted(false);
        btnSuma.setContentAreaFilled(false);
        btnSuma.setFocusPainted(false);
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/menos.png"))); // NOI18N
        btnResta.setBorder(null);
        btnResta.setBorderPainted(false);
        btnResta.setContentAreaFilled(false);
        btnResta.setFocusPainted(false);
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnMultiplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/asterisco.png"))); // NOI18N
        btnMultiplicacion.setBorder(null);
        btnMultiplicacion.setBorderPainted(false);
        btnMultiplicacion.setContentAreaFilled(false);
        btnMultiplicacion.setFocusPainted(false);
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });

        btnDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/barra-oblicua.png"))); // NOI18N
        btnDivision.setBorder(null);
        btnDivision.setBorderPainted(false);
        btnDivision.setContentAreaFilled(false);
        btnDivision.setFocusPainted(false);
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnRetroceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/simbolo-menor-que.png"))); // NOI18N
        btnRetroceso.setBorder(null);
        btnRetroceso.setBorderPainted(false);
        btnRetroceso.setContentAreaFilled(false);
        btnRetroceso.setFocusPainted(false);
        btnRetroceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocesoActionPerformed(evt);
            }
        });

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/letra-c.png"))); // NOI18N
        btnBorrar.setBorder(null);
        btnBorrar.setBorderPainted(false);
        btnBorrar.setContentAreaFilled(false);
        btnBorrar.setFocusPainted(false);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/mayor-que-el-simbolo.png"))); // NOI18N
        btnEspecial.setBorder(null);
        btnEspecial.setBorderPainted(false);
        btnEspecial.setContentAreaFilled(false);
        btnEspecial.setFocusPainted(false);
        btnEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNumerosLayout = new javax.swing.GroupLayout(panelNumeros);
        panelNumeros.setLayout(panelNumerosLayout);
        panelNumerosLayout.setHorizontalGroup(
            panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNumerosLayout.createSequentialGroup()
                .addGroup(panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNumerosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelNumerosLayout.createSequentialGroup()
                                .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelNumerosLayout.createSequentialGroup()
                                .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelNumerosLayout.createSequentialGroup()
                                .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelNumerosLayout.createSequentialGroup()
                                .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNumerosLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(btnRetroceso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNumerosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelNumerosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        panelNumerosLayout.setVerticalGroup(
            panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNumerosLayout.createSequentialGroup()
                .addGroup(panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRetroceso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelNumerosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNumerosLayout.createSequentialGroup()
                        .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNumerosLayout.createSequentialGroup()
                        .addGroup(panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lblSecundario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblResultado.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelEspeciales.setBackground(new java.awt.Color(130, 130, 130));
        panelEspeciales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnParentesisInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/soporte-abierto.png"))); // NOI18N
        btnParentesisInicio.setBorder(null);
        btnParentesisInicio.setBorderPainted(false);
        btnParentesisInicio.setContentAreaFilled(false);
        btnParentesisInicio.setFocusPainted(false);
        btnParentesisInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentesisInicioActionPerformed(evt);
            }
        });

        btnParentesisFin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/cerrar-soporte.png"))); // NOI18N
        btnParentesisFin.setBorder(null);
        btnParentesisFin.setBorderPainted(false);
        btnParentesisFin.setContentAreaFilled(false);
        btnParentesisFin.setFocusPainted(false);
        btnParentesisFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentesisFinActionPerformed(evt);
            }
        });

        btnRaiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/raiz-cuadrada.png"))); // NOI18N
        btnRaiz.setBorder(null);
        btnRaiz.setBorderPainted(false);
        btnRaiz.setContentAreaFilled(false);
        btnRaiz.setFocusPainted(false);
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        btnPotencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/signo-de-intercalacion.png"))); // NOI18N
        btnPotencia.setBorder(null);
        btnPotencia.setBorderPainted(false);
        btnPotencia.setContentAreaFilled(false);
        btnPotencia.setFocusPainted(false);
        btnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenciaActionPerformed(evt);
            }
        });

        btnComa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/imagenes/coma.png"))); // NOI18N
        btnComa.setBorder(null);
        btnComa.setBorderPainted(false);
        btnComa.setContentAreaFilled(false);
        btnComa.setFocusPainted(false);
        btnComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEspecialesLayout = new javax.swing.GroupLayout(panelEspeciales);
        panelEspeciales.setLayout(panelEspecialesLayout);
        panelEspecialesLayout.setHorizontalGroup(
            panelEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEspecialesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEspecialesLayout.createSequentialGroup()
                        .addComponent(btnParentesisInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnParentesisFin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEspecialesLayout.createSequentialGroup()
                        .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnComa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        panelEspecialesLayout.setVerticalGroup(
            panelEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEspecialesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnParentesisInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParentesisFin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btnComa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelEspeciales1.setBackground(new java.awt.Color(130, 130, 130));
        panelEspeciales1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDecTexto.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblDecTexto.setText("DEC");

        lblOctTexto.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblOctTexto.setText("OCT");

        lblBinTexto.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblBinTexto.setText("BIN");

        lblHexTexto.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblHexTexto.setText("HEX");

        lblHexConvertido.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        lblDecConvertido.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        lblOctConvertido.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        lblBinConvertido.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelEspeciales1Layout = new javax.swing.GroupLayout(panelEspeciales1);
        panelEspeciales1.setLayout(panelEspeciales1Layout);
        panelEspeciales1Layout.setHorizontalGroup(
            panelEspeciales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEspeciales1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEspeciales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDecTexto)
                    .addComponent(lblOctTexto)
                    .addComponent(lblBinTexto)
                    .addComponent(lblHexTexto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEspeciales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDecConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOctConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBinConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHexConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panelEspeciales1Layout.setVerticalGroup(
            panelEspeciales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEspeciales1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelEspeciales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEspeciales1Layout.createSequentialGroup()
                        .addComponent(lblDecConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(lblOctConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(lblBinConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(lblHexConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(panelEspeciales1Layout.createSequentialGroup()
                        .addComponent(lblDecTexto)
                        .addGap(5, 5, 5)
                        .addComponent(lblOctTexto)
                        .addGap(5, 5, 5)
                        .addComponent(lblBinTexto)
                        .addGap(5, 5, 5)
                        .addComponent(lblHexTexto)
                        .addGap(5, 5, 5))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelEspeciales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(panelNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(panelEspeciales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        lblResultado.setText("");
        lblSecundario.setText("");
        lblDecConvertido.setText("");
        lblBinConvertido.setText("");
        lblOctConvertido.setText("");
        lblHexConvertido.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnRetrocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocesoActionPerformed

        if (lblSecundario.getText().length() != 0) {
            String texto = lblSecundario.getText().substring(0, lblSecundario.getText().length() - 1);
            lblSecundario.setText(texto);
            if (texto.length() >= 1) {
                btnIgual.doClick();
            }
        }
    }//GEN-LAST:event_btnRetrocesoActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        agregarNumero("/");
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        agregarNumero("*");
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        agregarNumero("-");
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        agregarNumero("+");
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        try {
            resultado = se.eval(lblSecundario.getText()).toString();
            lblResultado.setText(resultado);
            actualizarNumeros();
        } catch (ScriptException ex) {

        }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum0ActionPerformed
        lblResultado.setText("0");
        agregarNumero("0");
    }//GEN-LAST:event_btnNum0ActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        agregarNumero(".");
        lblResultado.setText(".");
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum9ActionPerformed
        lblResultado.setText("9");
        agregarNumero("9");
    }//GEN-LAST:event_btnNum9ActionPerformed

    private void btnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum8ActionPerformed
        lblResultado.setText("8");
        agregarNumero("8");
    }//GEN-LAST:event_btnNum8ActionPerformed

    private void btnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum7ActionPerformed
        lblResultado.setText("7");
        agregarNumero("7");
    }//GEN-LAST:event_btnNum7ActionPerformed

    private void btnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum6ActionPerformed
        lblResultado.setText("6");
        agregarNumero("6");
    }//GEN-LAST:event_btnNum6ActionPerformed

    private void btnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum5ActionPerformed
        lblResultado.setText("5");
        agregarNumero("5");
    }//GEN-LAST:event_btnNum5ActionPerformed

    private void btnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum4ActionPerformed
        lblResultado.setText("4");
        agregarNumero("4");
    }//GEN-LAST:event_btnNum4ActionPerformed

    private void btnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum3ActionPerformed
        lblResultado.setText("3");
        agregarNumero("3");
    }//GEN-LAST:event_btnNum3ActionPerformed

    private void btnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum2ActionPerformed
        lblResultado.setText("2");
        agregarNumero("2");
    }//GEN-LAST:event_btnNum2ActionPerformed

    private void btnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum1ActionPerformed
        lblResultado.setText("1");
        agregarNumero("1");
    }//GEN-LAST:event_btnNum1ActionPerformed

    private void btnEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecialActionPerformed
        if (!activo) {
            this.setSize(502, 474);
            activo = true;
        } else {
            this.setSize(290, 474);
            activo = false;
        }
    }//GEN-LAST:event_btnEspecialActionPerformed

    private void btnParentesisInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentesisInicioActionPerformed
        agregarNumero("(");
    }//GEN-LAST:event_btnParentesisInicioActionPerformed

    private void btnParentesisFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentesisFinActionPerformed
        agregarNumero(")");
    }//GEN-LAST:event_btnParentesisFinActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        agregarNumero("Math.sqrt(");
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaActionPerformed
        agregarNumero("Math.pow(");
    }//GEN-LAST:event_btnPotenciaActionPerformed

    private void btnComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComaActionPerformed
        agregarNumero(",");
    }//GEN-LAST:event_btnComaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new calculadora().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnComa;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnEspecial;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnNum0;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnNum2;
    private javax.swing.JButton btnNum3;
    private javax.swing.JButton btnNum4;
    private javax.swing.JButton btnNum5;
    private javax.swing.JButton btnNum6;
    private javax.swing.JButton btnNum7;
    private javax.swing.JButton btnNum8;
    private javax.swing.JButton btnNum9;
    private javax.swing.JButton btnParentesisFin;
    private javax.swing.JButton btnParentesisInicio;
    private javax.swing.JButton btnPotencia;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnRetroceso;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel lblBinConvertido;
    private javax.swing.JLabel lblBinTexto;
    private javax.swing.JLabel lblDecConvertido;
    private javax.swing.JLabel lblDecTexto;
    private javax.swing.JLabel lblHexConvertido;
    private javax.swing.JLabel lblHexTexto;
    private javax.swing.JLabel lblOctConvertido;
    private javax.swing.JLabel lblOctTexto;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSecundario;
    private javax.swing.JPanel panelEspeciales;
    private javax.swing.JPanel panelEspeciales1;
    private javax.swing.JPanel panelNumeros;
    // End of variables declaration//GEN-END:variables

}
